In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# import numpy as np
# from scipy.special import logsumexp
# from tqdm import tqdm

# dim_z = dim_sc = int(2)
# dim_x = 51

# dim_ai = int(3)
# dim_sai = int(2)

# theta2 = [0.949,0.012]
# p0 = [0.039,0.333,0.590]
# p1=[0.181,0.757,0.061]
# params_true = p0 + p1 +theta2
# # dynamic = Dynamic(params_true)
# theta1_true = [9.243,0.226,1.164]    



# #z_old = np.kron(np.ones(dim_x,dtype = int),np.arange(dim_z,dtype = int)) 
# #x_old = np.kron(np.linspace(0,1,num = dim_x),np.ones(dim_z))


# def Dynamic(params):
#     # theta2 = np.around(params[6:8],3)
#     # p0 = np.around(params[0:3],3)
#     # p1 = np.around(params[3:6],3)
#     theta2 = params[6:8]
#     p0 = params[0:3]
#     p1 = params[3:6]
    
#     # dynamic: [2*2*2,3*3,2*2*2*2] [sa1 * sa2 * sc , action1 * action2, sa1' * sa2' * sc' * zc]
#     # stranc : [2*2*2, 3*3, 2*2*2] [sa1*sa2*sc, action1 * action2, sa1' * sa2' *sc']
#     # ztranc : [2*2*2, 3*3, 2] [sa1'*sa2'*sc', action1 * action2, zc ]

#     stranc = np.zeros([dim_sai * dim_sai * dim_sc, dim_ai * dim_ai, dim_sai * dim_sai * dim_sc])
#     ztranc = np.zeros([dim_sai * dim_sai * dim_sc, dim_ai * dim_ai, dim_z])

#     stranc[0:(dim_sai*dim_sai),2*dim_ai + 2,0] = 1 #sc = 0, a = (2,2)
#     stranc[(dim_sai *dim_sai):(2*dim_sai *dim_sai),2*dim_ai + 2,dim_sai *dim_sai] = 1 #sc = 1, a = (2,2)
#     stranc[0:(dim_sai*dim_sai),2*dim_ai ,0] = 1 #sc = 0, a = (0,*) or (*,0)
#     stranc[(dim_sai *dim_sai):(2*dim_sai *dim_sai),2*dim_ai + 2,dim_sai *dim_sai] = 1 #sc = 1, a = (2,2)


#     ztranc[0,0:dim_z,:] = np.kron(np.ones(2),p0[0]*np.eye(dim_z,k=0) + p0[1] *np.eye(dim_z,k=1) + p0[2]*np.eye(dim_z,k=2) + (1-np.sum(p0)) *np.eye(dim_z,k=3))
#     ztranc[1,0:dim_z,:] = np.kron(np.ones(2),p1[0]*np.eye(dim_z,k=0) + p1[1] *np.eye(dim_z,k=1) + p1[2]*np.eye(dim_z,k=2) + (1-np.sum(p1)) *np.eye(dim_z,k=3))

#     ztranc[:,dim_z-1,dim_z-1] = np.ones(2)
#     ztranc[:,dim_z-2,dim_z-1] = 1-ztranc[:,dim_z-2,dim_z-2]
#     ztranc[:,dim_z-3,dim_z-1] = 1-np.sum(ztranc[:,dim_z-3,:dim_z-1],axis=1)


#     ztranc[:,dim_z:2*dim_z,0] = np.ones([2,dim_z])

#     stranc[0,0:dim_z,:] = np.hstack([theta2[0] *np.ones([dim_z,dim_z]),(1-theta2[0]) *np.ones([dim_z,dim_z])])
#     stranc[1,0:dim_z,:] = np.hstack([theta2[1] *np.ones([dim_z,dim_z]),(1-theta2[1]) *np.ones([dim_z,dim_z])])
#     stranc[:,dim_z:2*dim_z,0] = np.ones([2,dim_z])
#     return stranc*ztranc#

# def SigmaBelief(params,x0,action,state,time=None):
#     dynamic = Dynamic(params)

#     if time ==None:
#         x_tol = np.zeros([x0.shape[0],dim_z])
#         sigma_tol = np.zeros([x0.shape[0],dim_z])

#         z = state
#         #z_prime = np.arange(dim_z) 

#         a = action

#         #print(x0*dynamic[0,z+a*dim_z,0:dim_z ])
      
#         x_tol = (x0 * dynamic[0,z+a*dim_z, 0:dim_z ].T + (1-x0) * dynamic[1,z+a*dim_z,0:dim_z].T).T
#         sigma_tol = x_tol + (x0  * dynamic[0,z+ a*dim_z, dim_z:2*dim_z].T + (1-x0 ) * dynamic[1,z+ a*dim_z, dim_z:2*dim_z].T).T
        
#         x_tol[np.where(sigma_tol!=0)] = x_tol[np.where(sigma_tol!=0)]/sigma_tol[np.where(sigma_tol!=0)] 

#         coef_floor = (np.floor(x_tol*(dim_x-1))/(dim_x-1))-(np.ceil(x_tol*(dim_x-1))/(dim_x-1))
#         coef_floor[np.where(coef_floor!=0)] = (coef_floor -np.ceil(coef_floor*(dim_x-1))/(dim_x-1))[np.where(coef_floor!=0)]/ coef_floor[np.where(coef_floor!=0)]
#         x_tol = [x_tol,coef_floor]


#     elif time ==1:
#         x_tol = x0
#         sigma_tol = np.zeros(action.shape)

#         z = state[0,:]
#         z_prime = state[1,:]
#         a = action
        
#         x_temp = x_tol  * dynamic[0,z+ a*dim_z, z_prime +0] + (1-x_tol ) * dynamic[1,z+ a*dim_z, z_prime +0]
#         sigma_tol = x_temp + x_tol  * dynamic[0,z+ a*dim_z, z_prime +dim_z] + (1-x_tol ) * dynamic[1,z+ a*dim_z, z_prime +dim_z]
#         x_tol  = x_temp/sigma_tol
#             #print(x_temp,sigma_tol,x_tol[i,:],z,a,z_prime)

#         coef_floor = (np.floor(x_tol*(dim_x-1))/(dim_x-1))-(np.ceil(x_tol*(dim_x-1))/(dim_x-1))
#         coef_floor[np.where(coef_floor!=0)] = (coef_floor -np.ceil(coef_floor*(dim_x-1))/(dim_x-1))[np.where(coef_floor!=0)]/ coef_floor[np.where(coef_floor!=0)]
#         x_tol = [x_tol,coef_floor] 
#     else:

#         # print(time)
#         x_tol = np.zeros(state.shape)
#         x_tol[0,:] = x0
#         sigma_tol = np.zeros([time-1,action.shape[1]])   
#         for i in range(1,time):
#           z = state[i-1,:]
#           z_prime = state[i,:]
#           a = action[i-1,:]
          
#           x_temp = x_tol[i-1,:]  * dynamic[0,z+ a*dim_z, z_prime +0] + (1-x_tol[i-1,:] ) * dynamic[1,z+ a*dim_z, z_prime +0] 
#           sigma_tol[i-1,:] = x_temp + x_tol[i-1,:]  * dynamic[0,z+ a*dim_z, z_prime +dim_z] + (1-x_tol[i-1,:] ) * dynamic[1,z+ a*dim_z, z_prime +dim_z]
#           x_tol[i,:]  = x_temp/sigma_tol[i-1,:]
#           # if(i==1):
#           #   print(x_tol[0,9],z[9],z_prime[9],x_temp[9],a[9],dynamic[1,z[9]+ a[9]*dim_z, z_prime[9] +0] )
#         coef_floor = (np.floor(x_tol*(dim_x-1))/(dim_x-1))-(np.ceil(x_tol*(dim_x-1))/(dim_x-1))
#         coef_floor[np.where(coef_floor!=0)] = (coef_floor -np.ceil(coef_floor*(dim_x-1))/(dim_x-1))[np.where(coef_floor!=0)]/ coef_floor[np.where(coef_floor!=0)]
#         x_tol = [x_tol,coef_floor] 
#         #print(x_tol[0].shape,coef_floor.shape)   


#     return sigma_tol,x_tol

# #print(x_old)

# #(a0_sigma,a0_xnew),(a1_sigma,a1_xnew) = SigmaBelief(params_true,x_old,0,z_old,None),SigmaBelief(params_true,x_old,1,z_old,None)

# def Reward(theta1):
#     reward = np.zeros([dim_x*dim_z,2]) 

#     Rc = theta1[0]
#     r0 = theta1[1]
#     r1 = theta1[2]
#     z_old = np.kron(np.ones(dim_x,dtype = int),np.arange(dim_z,dtype = int)) 
#     x_old = np.kron(np.linspace(0,1,num = dim_x),np.ones(dim_z))

#     reward[:,0] = - 0.001*r0*z_old*x_old - 0.001 *r1 *z_old*(1-x_old)
#     reward[:,1] = -Rc

#     return reward 

# #print(Reward(theta1_true))
# #(a0_sigma,a0_xnew),(a1_sigma,a1_xnew) = SigmaBelief(params_true,x_old,0,z_old,None),SigmaBelief(params_true,x_old,1,z_old,None)

# def Qfunc(theta1,a0_sigma,a0_xnew,a1_sigma,a1_xnew,Q_old = np.zeros([dim_z*dim_x,2]),beta = 0.9999,gamma = 0.5772,max_item = 1000,thread = 0.25*1e-3):
#     #print(x_old)
#     r = Reward(theta1)
#     Q_new = r.copy()

#     for i in range(max_item):
#         Q_prime = np.vstack([a0_xnew[1] * Q_old[np.intc(np.floor(a0_xnew[0]*(dim_x-1))) * dim_z +np.arange(dim_z),0]+\
#                             (1-a0_xnew[1]) * Q_old[np.intc(np.ceil(a0_xnew[0]*(dim_x-1))) * dim_z +np.arange(dim_z),0],
#                             a1_xnew[1] * Q_old[np.intc(np.floor(a1_xnew[0]*(dim_x-1))) * dim_z +np.arange(dim_z),1]+\
#                             (1-a1_xnew[1]) * Q_old[np.intc(np.ceil(a1_xnew[0]*(dim_x-1))) * dim_z +np.arange(dim_z),1]])
#         Q_prime = gamma + logsumexp( np.reshape(Q_prime,[2,dim_x*dim_z,dim_z]),axis=0 )
#         Q_new[:,0] =  r[:,0] + beta * np.sum(a0_sigma* Q_prime,axis=1)
#         Q_new[:,1] =  r[:,1] + beta *(gamma + logsumexp(Q_old[(dim_x-1)*dim_z+0,:]))#r[:,1] + beta * np.sum(a1_sigma* Q_prime,axis=1)

#         pi_old = np.exp(Q_old[:,0]-Q_old[:,1])/(np.exp(Q_old[:,0]-Q_old[:,1]) +1)
#         pi_new = np.exp(Q_new[:,0]-Q_new[:,1])/(np.exp(Q_new[:,0]-Q_new[:,1]) +1)
#         error = np.max(np.abs(pi_old-pi_new))

#         #error1 = np.max(np.abs((Q_old[:,0]-Q_old[:,1])-(Q_new[:,0]-Q_new[:,1])))

#         Q_old = Q_new.copy()
#         # if i>max_item:
#         #   break
#         # i = i+1
#         #print(i,error,error1)
#         if error <= thread: #or error1 <=thread*5:
#           break


#     return Q_new, pi_new

In [ ]:
# import pandas as pd
# def DataGenerate(BeliefSize,SampleSize, TimePeriod, theta1 = [9.243,0.226,1.164], theta2 = [0.949,0.012],\
#                 p0 = [0.039,0.333,0.590],p1=[0.181,0.757,0.061],rand_status = False):
    
#     condition = np.zeros([TimePeriod,SampleSize],dtype = int) #hidden state: 0,1
#     state = np.zeros([TimePeriod,SampleSize],dtype = int ) #mileage: 175:0,...,174
#     x = np.ones([TimePeriod,SampleSize])#belief: s = 0 prob # 删除

#     if rand_status: # s0 z0 x0
#         x[0,:] = np.kron(np.linspace(0, 1,num= BeliefSize),np.ones(int(SampleSize/BeliefSize)))
#         #x[:,0] = np.kron(np.random.uniform(size = dim_x0),np.ones(int(SampleSize/dim_x0)))

#         state[0,:] = np.random.choice(np.arange(20,dtype= int),size = SampleSize,p=np.ones(20)/20)#uniform(0,20)
#         pis =0.9509143407122231#np.random.uniform()
#         condition[0,:] = np.random.choice([0,1],size = SampleSize, p = [pis,1-pis])#0000
#     else:
#         pis = 1
#     action = np.zeros([TimePeriod,SampleSize],dtype = int)
#     rho = 1
#     print("generate Q")
#     params = p0 + p1 + theta2 
#     (a0_sigma,a0_xnew),(a1_sigma,a1_xnew) = SigmaBelief(params,x_old,0,z_old,None),SigmaBelief(params,x_old,1,z_old,None)
#     Q,_ = Qfunc(theta1,a0_sigma,a0_xnew,a1_sigma,a1_xnew) # Q function Q(x,a) --> interpolation 
#     #pchoice =self.choice_prob(rho,Q) # z = 0, x= 0, 0.1, 0.2,....,1, z = 1, x = 0,...,1 pi
#     print("generate dataset")

#     #t=0
#     coef_floor = (np.floor(x[0,:]*(dim_x-1))/(dim_x-1))-(np.ceil(x[0,:]*(dim_x-1))/(dim_x-1))
#     coef_floor[np.where(coef_floor!=0)] = (coef_floor -np.ceil(coef_floor*(dim_x-1))/(dim_x-1))[np.where(coef_floor!=0)]/ coef_floor[np.where(coef_floor!=0)]

#     Q_prime = np.vstack([coef_floor* Q[np.intc(np.floor(x[0,:]*(dim_x-1))) * dim_z +state[0,:],0]+\
#                         (1-coef_floor) * Q[np.intc(np.ceil(x[0,:]*(dim_x-1))) * dim_z +state[0,:],0],
#                         coef_floor * Q[np.intc(np.floor(x[0,:]*(dim_x-1))) * dim_z +state[0,:],1]+\
#                         (1-coef_floor) * Q[np.intc(np.ceil(x[0,:]*(dim_x-1))) * dim_z +state[0,:],1]]).T.copy()
    
#     pi0 = np.exp(Q_prime[:,0]-Q_prime[:,1])/(np.exp(Q_prime[:,0]-Q_prime[:,1])+1).copy()
#     action[0,:] = np.intc(np.random.uniform(0,1,size = SampleSize) > pi0).copy()

#     for t in tqdm(range(1,TimePeriod)):

#         state[t,np.where(action[t-1,:]==1)] = 0
#         condition[t,np.where(action[t-1,:]==1)] = 0 

#         delta_z0 = np.random.choice([0,1,2,3],p=[p0[0],p0[1],p0[2],1-np.sum(p0)],size=SampleSize).copy()
#         delta_s0 = np.random.choice([0,1],p=[theta2[0],1-theta2[0]],size=SampleSize).copy()
#         state[t,np.where((action[t-1,:]==0)*(condition[t-1,:] == 0)==1)] = state[t-1,np.where((action[t-1,:]==0)*(condition[t-1,:] == 0)==1)] + delta_z0[np.where((action[t-1,:]==0)*(condition[t-1,:] == 0)==1)]
#         condition[t,np.where((action[t-1,:]==0)*(condition[t-1,:] == 0)==1)] = delta_s0[np.where((action[t-1,:]==0)*(condition[t-1,:] == 0)==1)]

#         delta_z1 = np.random.choice([0,1,2,3],p=[p1[0],p1[1],p1[2],1-np.sum(p1)],size=SampleSize).copy()
#         delta_s1 = np.random.choice([0,1],p=[theta2[1],1-theta2[1]],size=SampleSize).copy()
#         state[t,np.where((action[t-1,:]==0)*(condition[t-1,:] == 1)==1)] = state[t-1,np.where((action[t-1,:]==0)*(condition[t-1,:] == 1)==1)] + delta_z1[np.where((action[t-1,:]==0)*(condition[t-1,:] == 1)==1)]
#         condition[t,np.where((action[t-1,:]==0)*(condition[t-1,:] == 1)==1)] = delta_s1[np.where((action[t-1,:]==0)*(condition[t-1,:] == 1)==1)]

#         state[t,np.where(state[t,:]>=(dim_z-1))] = 174


#         _,temp = SigmaBelief(params,x[t-1,:],action[t-1,:],state[t-1:t+1,:],time=1)
#         x[t,:] = temp[0].copy()
        
#         coef_floor = temp[1]
#         #print(x[t,:]*(dim_x-1),np.floor(x[t,:]*(dim_x-1)), dim_z,state[t,:])

#         Q_prime = np.vstack([coef_floor* Q[np.intc(np.floor(x[t,:]*(dim_x-1))) * dim_z +state[t,:],0]+\
#                             (1-coef_floor) * Q[np.intc(np.ceil(x[t,:]*(dim_x-1))) * dim_z +state[t,:],0],
#                             coef_floor * Q[np.intc(np.floor(x[t,:]*(dim_x-1))) * dim_z +state[t,:],1]+\
#                             (1-coef_floor) * Q[np.intc(np.ceil(x[t,:]*(dim_x-1))) * dim_z +state[t,:],1]]).T
    
#         pi0 = np.exp(Q_prime[:,0]-Q_prime[:,1])/(np.exp(Q_prime[:,0]-Q_prime[:,1])+1)
#         action[t,:] = np.intc(np.random.uniform(0,1,size = SampleSize) > pi0).copy()

            


#     state_new = np.reshape(state.T,[-1])
#     action_new = np.reshape(action.T,[-1])
#     data = {'state':state_new,'action':action_new}
#     dat_new = pd.DataFrame(data=data)
    
#     return dat_new,{'state':state,'action':action.T,'hidden':condition.T,'belief':x.T,'pis':pis}



# Original without Sa
(Recovering for dynamics still has problems)

In [2]:
import numpy as np
import random as rn
import itertools as its
from sklearn.preprocessing import normalize
from tqdm import tqdm

class DataGeneration(object):
    def __init__(self, theta ,N,T,x0_dim):
      self.reward = theta #s a1 a2
      self.x0_dim = x0_dim

      self.dygame = np.zeros([2,2,2,2,2]) #st,at1, at2,st+1, zt+1
      ind = 0
      for st, at1, at2 in its.product(range(2),range(2),range(2)):
        ind = ind + 1
        rn.seed(ind)
        prob = rn.choices(np.arange(11), weights=None, cum_weights=None, k=4)
        self.dygame[st,at1,at2,:,:] = np.reshape(prob/np.sum(prob),[2,2])
      
      self.N = N
      self.T = T
      
      self.gamma = 0.5772
      self.beta = 0.9

      self.blief = 31
      self.iniccp = np.ones([self.blief,2])/2#np.vstack([np.ones(self.blief),np.zeros(self.blief)]).T

    def rw(self,s,a1,a2,theta2): # sc in {0,1}, a1,a2 in {0,1}
      theta2 = np.reshape(theta2,[2,2,2])
      return theta2[s,a1,a2]

    def siglam(self,z,x,a1,a2,theta1):
      theta1 = np.reshape(theta1,[2,2,2,2,2])
      lambd = theta1[:,a1,a2,:,z].T.dot([x,1-x])
      sigma = np.sum(lambd)
      return lambd[0]/sigma, sigma

    def PartCCP(self,ccp,ccpc,theta2,theta1, maxiter,thread1):
      Q = np.zeros([self.blief,2])
      #print(maxiter)    
      for j in range(maxiter):
        Q_old = Q.copy()
        V = self.gamma + np.log(np.sum(np.exp(Q),axis=1))
        
        for indx, inda in its.product(self.x,range(2)):
          
          l = np.zeros([2,2])#z,a1
          s = np.zeros([2,2])
          V_tep = np.zeros([2,2])
          for indl, inds in its.product(range(2),range(2)): #z , a2
            
            l[indl,inds],s[indl,inds] = (ccp==2)*self.siglam(indl,indx,inds,inda,theta1)+\
                                        (ccp==1)*self.siglam(indl,indx,inda,inds,theta1) #z , a1
            fl = int(np.floor(l[indl,inds] * (self.blief-1)))
            if fl == self.blief-1:
              V_tep[indl,inds] = V[fl]
            else: 
              V_tep[indl,inds] = V[fl] * (l[indl,inds]*(self.blief-1) - fl) + V[fl+1]* (1 + fl -l[indl,inds]*(self.blief-1)) 
          
          V_tep = V_tep * s
          
          ind = int(indx *(self.blief-1))
                          
          Q[ind,inda] = (ccp==2)*(ccpc[ind,0] *( indx* self.rw(0,0,inda,theta2) + (1-indx) * self.rw(1,0,inda,theta2) + self.beta * np.sum(V_tep[:,0])) +\
                          ccpc[ind,1] * (indx* self.rw(0,1,inda,theta2) + (1-indx) * self.rw(1,1,inda,theta2) + self.beta * np.sum(V_tep[:,1]))) +\
                        (ccp==1)*(ccpc[ind,0] *( indx* self.rw(0,inda,0,theta2) + (1-indx) * self.rw(1,inda,0,theta2) + self.beta * np.sum(V_tep[:,0])) +\
                           ccpc[ind,1] * (indx* self.rw(0,inda,1,theta2) + (1-indx) * self.rw(1,inda,1,theta2) +self.beta * np.sum(V_tep[:,1])))

        if np.max(np.abs(Q-Q_old))<=thread1:
          break
      ccpcc = normalize(np.exp(Q), norm='l1',axis=1)#np.exp(Q1)/(np.sum(np.exp(Q1),axis=1)) 
      return ccpcc

    def PerfectMarkov(self,ccp,iniCCP1,theta2,theta1, maxiter = 100,thread1 = 0.01,thread2 = 1e-4):      
      self.x = np.linspace(0,1,self.blief)     
      ccp1 = iniCCP1
      ccp2 = iniCCP1
      #for i in tqdm(range(maxiter)):
      for i in range(maxiter):

        ccp1_old = ccp1.copy()
        ccp2_old = ccp2.copy()
        if ccp==1:
          ccp2 = self.PartCCP(ccp+1,ccp1,theta2,theta1,maxiter,thread1)
          ccp1 = self.PartCCP(ccp,ccp2,theta2,theta1,maxiter,thread1)
        else:
          ccp1 = self.PartCCP(ccp-1,ccp2,theta2,theta1,maxiter,thread1)
          ccp2 = self.PartCCP(ccp,ccp1,theta2,theta1,maxiter,thread1)
       
        # Q2 = np.zeros([self.blief,2])
        
        # for j in range(maxiter):
        #   Q2_old = Q2.copy()
        #   V2 = self.gamma + np.log(np.sum(np.exp(Q2),axis=1))
          
        #   for indx, inda in its.product(x,range(2)):
            
        #     l2 = np.zeros([2,2])#z,a1
        #     s2 = np.zeros([2,2])
        #     V2_tep = np.zeros([2,2])
        #     for indl, inds in its.product(range(2),range(2)): #z , a2
              
        #       l2[indl,inds],s2[indl,inds] = self.siglam(indl,indx,inds,inda,theta1) #z , a1
        #       fl = int(np.floor(l2[indl,inds] * (self.blief-1)))
        #       if fl == self.blief-1:
        #         V2_tep[indl,inds] = V2[fl]
        #       else: 
        #         V2_tep[indl,inds] = V2[fl] * (l2[indl,inds]*(self.blief-1) - fl) + V2[fl+1]* (1 + fl -l2[indl,inds]*(self.blief-1)) 
            
        #     V2_tep = V2_tep * s2
            
        #     ind = int(indx *(self.blief-1))
                            
        #     Q2[ind,inda] = ccp1[ind,0] *( indx* self.rw(0,0,inda,theta2) + (1-indx) * self.rw(1,0,inda,theta2) + self.beta * np.sum(V2_tep[:,0])) +\
        #                     ccp1[ind,1] * (indx* self.rw(0,1,inda,theta2) + (1-indx) * self.rw(1,1,inda,theta2) + self.beta * np.sum(V2_tep[:,1]))

        #   if np.max(np.abs(Q2-Q2_old))<=thread1:
        #     break
        # ccp2 = normalize(np.exp(Q2), norm='l1',axis=1)#np.exp(Q1)/(np.sum(np.exp(Q1),axis=1))
        
        
        # Q1 = np.zeros([self.blief,2])        
        # for j in range(maxiter):
        #   Q1_old = Q1.copy()
        #   #Q2_old = Q2.copy()
          
        #   V1 = self.gamma + np.log(np.sum(np.exp(Q1),axis=1))
        #   for indx, inda in its.product(x,range(2)):
            
        #     l1 = np.zeros([2,2])#z,a2
        #     s1 = np.zeros([2,2])
        #     V1_tep = np.zeros([2,2])

        #     for indl, inds in its.product(range(2),range(2)): #z , a2
        #       ##print(siglam(indl,indx,inda,inds))
        #       l1[indl,inds],s1[indl,inds] = self.siglam(indl,indx,inda,inds,theta1)
        #       fl = int(np.floor(l1[indl,inds] * (self.blief-1)))
        #       if fl == self.blief-1:
        #        V1_tep[indl,inds] = V1[fl]
        #       else: 
        #        V1_tep[indl,inds] = V1[fl] * (l1[indl,inds]*(self.blief-1) - fl) + V1[fl+1]* (1 + fl -l1[indl,inds]*(self.blief-1)) 
            
        #     #print(indl)
        #     V1_tep = V1_tep * s1

        #     ind = int(indx *(self.blief-1))
        #     Q1[ind,inda] = ccp2[ind,0] *( indx* self.rw(0,inda,0,theta2) + (1-indx) * self.rw(1,inda,0,theta2) + \
        #                      self.beta * np.sum(V1_tep[:,0])) +\
        #                    ccp2[ind,1] * (indx* self.rw(0,inda,1,theta2) + (1-indx) * self.rw(1,inda,1,theta2) +\
        #                      self.beta * np.sum(V1_tep[:,1]))
                            
        #   #print(j,haha1)
        #   if np.max(np.abs(Q1-Q1_old))<=thread1:
        #     #print(i,j)
        #     #print(j,np.max(Q1),np.max(Q2),np.max(np.abs(Q1-Q1_old)),np.max(np.abs(Q2-Q2_old)))
        #     break
        #   #print(j,np.max(Q1),np.max(Q2),np.max(np.abs(Q1-Q1_old)),np.max(np.abs(Q2-Q2_old)))
        # ccp1 = normalize(np.exp(Q1), norm='l1',axis=1)#np.exp(Q1)/(np.sum(np.exp(Q1),axis=1))
        # #ccp2 = normalize(np.exp(Q2), norm='l1',axis=1)#np.exp(Q1)/(np.sum(np.exp(Q1),axis=1))


        if np.max(np.abs(ccp1-ccp1_old))<=thread2 and np.max(np.abs(ccp2-ccp2_old))<=thread2:
          #print(i,ccp1,ccp2)
          #print(i,np.max(ccp1),np.max(ccp2),np.max(np.abs(ccp1-ccp1_old)),np.max(np.abs(ccp2-ccp2_old)))
          break
        #print(i,ccp1,ccp2)  
        #print(i,np.max(ccp1),np.max(ccp2),np.max(np.abs(ccp1-ccp1_old)),np.max(np.abs(ccp2-ccp2_old)))
      if i == maxiter -1:
        print('fail to converge')
      return ccp1, ccp2, i


    def simulation(self):
      ccp1, ccp2,_ = self.PerfectMarkov(1,self.iniccp,self.reward,self.dygame)

      self.st = np.zeros([self.N,self.T+1],dtype = int)
      self.zt = np.zeros([self.N,self.T],dtype = int)
      self.a1t = np.zeros([self.N,self.T],dtype = int)
      self.a2t = np.zeros([self.N,self.T],dtype = int)
      self.belief = 1/2 * np.ones([self.N,self.T+1])
      self.belief[:,0] = np.kron(np.ones(int(self.N/self.x0_dim)),np.linspace(0,1,num = self.x0_dim))

      rn.seed(0)
      self.st[:,0] = rn.choices([0,1],[1/2,1/2], k = self.N)

      for ss in range(self.N):
        for t in range(self.T):
          fl = int(np.floor(self.belief[ss,t] * (self.blief-1)))
          if fl == self.blief-1:
            prob1 = ccp1[fl,:]
            prob2 = ccp2[fl,:]
          else: 
            prob1 = ccp1[fl,:] * (self.belief[ss,t] *(self.blief-1) - fl) + ccp1[fl+1,:]* (1 + fl -self.belief[ss,t]*(self.blief-1))
            prob2 = ccp2[fl,:] * (self.belief[ss,t] *(self.blief-1) - fl) + ccp2[fl+1,:]* (1 + fl -self.belief[ss,t]*(self.blief-1))
          
          self.a1t[ss,t] = rn.choices([0,1],prob1)[0]
          self.a2t[ss,t] = rn.choices([0,1],prob2)[0]

          prob3 = self.dygame[self.st[ss,t], self.a1t[ss,t],self.a2t[ss,t],:,:]#st,at1, at2,st+1, zt+1

          self.st[ss,t+1], self.zt[ss,t] = rn.choices([[0,0],[0,1],[1,0],[1,1]], np.reshape(prob3,[4,1]))[0]
          self.belief[ss,t+1],_ = self.siglam(self.zt[ss,t],self.belief[ss,t],self.a1t[ss,t],self.a2t[ss,t],self.dygame)
      return {'state':self.st, 'observation':self.zt, 'action1':self.a1t, 'action2': self.a2t,'belief':self.belief}

In [5]:
# np.random.seed(0)
# theta2 = np.random.uniform(1,5,8)
# theta2[2] = theta2[1]
# theta2[6] = theta2[5]
# print(theta2)

In [6]:
import pandas as pd

np.random.seed(0)
theta2 = np.random.uniform(1,5,8)
theta2[2] = theta2[1]
theta2[6] = theta2[5]
#print(theta)
theta2 = np.reshape(pd.Series(theta2).round(2).to_numpy(),[2,2,2])
#print(theta)
N = 1500
T = 30
x0_dim = 50
dataset = DataGeneration(theta2,N,T,x0_dim)
res = dataset.simulation()
print(res)

{'state': array([[1, 1, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 0, 1],
       ...,
       [1, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 1, ..., 1, 1, 1]]), 'observation': array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 1],
       [1, 0, 1, ..., 1, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]]), 'action1': array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 0, 1],
       [1, 0, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 1, 1, 0],
       [0, 1, 1, ..., 0, 0, 1]]), 'action2': array([[1, 1, 0, ..., 0, 1, 0],
       [1, 0, 1, ..., 1, 1, 0],
       [1, 0, 1, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 1, 0],
       [1, 1, 0, ..., 1, 1, 0]]), 'belief': array([[0.        , 0.58823529, 0.56213018, ..., 0.55680909, 0.9233022 ,
        0.78891652],
       [0.02040816, 0.587

In [7]:
##############Recover###############
# haha1 = np.ones([blief,2])/2
# PolicyFunc = lambda theta_try : PerfectMarkov(haha1, haha1,theta = theta_try, maxiter = 200,blief = blief)


def LogLike_MLE1(theta1,res=res,dataset=dataset,params=False):
  x0=res['belief'][:,0]
  obz = res['observation']
  ac1 = res['action1']
  ac2 = res['action2']
  #print('Compute Perfect Markov Equlibrium')
  # ccp1,ccp2,_ = PolicyFunc(theta)
  loglike = 0
  blief_x = x0.copy()

  # theta1_new = np.zeros([2,2,2,2,2])
  # for i in range(2):
  #   for j in range(2):
  #     for k in range(2):
  #       ind_ijk = ((i*2+j)*2+k)*3
  #       #print(ind_ijk)
  #       theta1_new[i,j,k,0,0] = theta1[ind_ijk]
  #       theta1_new[i,j,k,0,1] = theta1[ind_ijk+ 1]
  #       theta1_new[i,j,k,1,0] = theta1[ind_ijk+ 2]
  #       theta1_new[i,j,k,1,1] = 1- theta1_new[i,j,k,0,0]-theta1_new[i,j,k,0,1]-theta1_new[i,j,k,1,0]
  theta1_new = np.reshape(theta1,[2,2,2,2,2])
  #print('Compute Loglike')
  for ss in range(N):
    for t in range(T):

      blief_x[ss],sigma = dataset.siglam(obz[ss,t],blief_x[ss],ac1[ss,t],ac2[ss,t],theta1_new)
      loglike = loglike + np.log(sigma)#np.log(blief_x[ss])
  if params:
    print(-loglike)
  return -loglike

def LogLike_MLE2(theta2,theta1,res=res,dataset=dataset,params=True):
  theta2 = np.reshape(theta2,[2,2,2])
  x0=res['belief'][:,0]
  obz = res['observation']
  ac1 = res['action1']
  ac2 = res['action2']
  #print('Compute Perfect Markov Equlibrium')
  loglike = np.zeros(2)
  blief_x = x0.copy()
  # #print('Compute Loglike')
  # theta1_new = np.zeros([2,2,2,2,2])
  # for i in range(2):
  #   for j in range(2):
  #     for k in range(2):
  #       ind_ijk = ((i*2+j)*2+k)*3
  #       #print(ind_ijk)
  #       theta1_new[i,j,k,0,0] = theta1[ind_ijk]
  #       theta1_new[i,j,k,0,1] = theta1[ind_ijk+ 1]
  #       theta1_new[i,j,k,1,0] = theta1[ind_ijk+ 2]
  #       theta1_new[i,j,k,1,1] = 1- theta1_new[i,j,k,0,0]-theta1_new[i,j,k,0,1]-theta1_new[i,j,k,1,0]
  theta1_new = np.reshape(theta1,[2,2,2,2,2])

  for ccp in range(1,2):
    ccp1,ccp2,_ = dataset.PerfectMarkov(ccp,dataset.iniccp,theta2, theta1_new)
    #print(ccp1,ccp2)
    for ss in range(N):
      for t in range(T):
        fl = int(np.floor(blief_x[ss] * (dataset.blief-1)))
        if fl == dataset.blief-1:
          pi1 = ccp1[fl,ac1[ss,t]]
          pi2 = ccp2[fl,ac2[ss,t]]
        else: 
          pi1 = ccp1[fl,ac1[ss,t]] * (blief_x[ss] *(dataset.blief-1) - fl) + ccp1[fl+1,ac1[ss,t]]* (1 + fl -blief_x[ss] *(dataset.blief-1)) 
          pi2 = ccp2[fl,ac2[ss,t]] * (blief_x[ss] *(dataset.blief-1) - fl) + ccp2[fl+1,ac2[ss,t]]* (1 + fl -blief_x[ss] *(dataset.blief-1))
        loglike[ccp-1] = loglike[ccp-1] + np.log(pi1) + np.log(pi2)

        blief_x[ss],_ = dataset.siglam(obz[ss,t],blief_x[ss],ac1[ss,t],ac2[ss,t],theta1=theta1_new)
  if params:
    print(theta2,-loglike[0])
  return -np.max(loglike[0])


In [8]:
print(theta2)
print(dataset.dygame)
print(-LogLike_MLE1(dataset.dygame,params=False))
print(-LogLike_MLE2(theta2,dataset.dygame,params=True))

[[[3.2  3.86]
  [3.86 3.18]]

 [[2.69 3.58]
  [3.58 4.57]]]
[[[[[0.05       0.45      ]
    [0.4        0.1       ]]

   [[0.5        0.5       ]
    [0.         0.        ]]]


  [[[0.11764706 0.29411765]
    [0.23529412 0.35294118]]

   [[0.25       0.125     ]
    [0.5        0.125     ]]]]



 [[[[0.1875     0.25      ]
    [0.25       0.3125    ]]

   [[0.33333333 0.375     ]
    [0.20833333 0.08333333]]]


  [[[0.27272727 0.09090909]
    [0.63636364 0.        ]]

   [[0.1        0.5       ]
    [0.05       0.35      ]]]]]
-30024.16005438778
[[[3.2  3.86]
  [3.86 3.18]]

 [[2.69 3.58]
  [3.58 4.57]]] 60462.459270229876
-60462.459270229876


In [9]:

from scipy.optimize import minimize
#bounds = [[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1]]
from scipy.optimize import LinearConstraint

func1 = lambda theta1_dk: LogLike_MLE1(np.array([theta1_dk[0], 1- np.sum(dataset.dygame[0,0,0,1,:])-theta1_dk[0],dataset.dygame[0,0,0,1,0],dataset.dygame[0,0,0,1,1],\
                                                theta1_dk[1], 1- np.sum(dataset.dygame[0,0,1,1,:])-theta1_dk[1],dataset.dygame[0,0,1,1,0],dataset.dygame[0,0,1,1,1],\
                                                theta1_dk[2], 1- np.sum(dataset.dygame[0,1,0,1,:])-theta1_dk[2],dataset.dygame[0,1,0,1,0],dataset.dygame[0,1,0,1,1],\
                                                theta1_dk[3], 1- np.sum(dataset.dygame[0,1,1,1,:])-theta1_dk[3],dataset.dygame[0,1,1,1,0],dataset.dygame[0,1,1,1,1],\
                                                theta1_dk[4], 1- np.sum(dataset.dygame[1,0,0,1,:])-theta1_dk[4],dataset.dygame[1,0,0,1,0],dataset.dygame[1,0,0,1,1],\
                                                theta1_dk[5], 1- np.sum(dataset.dygame[1,0,1,1,:])-theta1_dk[5],dataset.dygame[1,0,1,1,0],dataset.dygame[1,0,1,1,1],\
                                                theta1_dk[6], 1- np.sum(dataset.dygame[1,1,0,1,:])-theta1_dk[6],dataset.dygame[1,1,0,1,0],dataset.dygame[1,1,0,1,1],\
                                                theta1_dk[7], 1- np.sum(dataset.dygame[1,1,1,1,:])-theta1_dk[7],dataset.dygame[1,1,1,1,0],dataset.dygame[1,1,1,1,1]]))

linear_constraint = LinearConstraint([[1,0,0,0,0,0,0,0],\
                                      [0,1,0,0,0,0,0,0],\
                                      [0,0,1,0,0,0,0,0],\
                                      [0,0,0,1,0,0,0,0],\
                                      [0,0,0,0,1,0,0,0],\
                                      [0,0,0,0,0,1,0,0],\
                                      [0,0,0,0,0,0,1,0],\
                                      [0,0,0,0,0,0,0,1]],\
                                     [0,(1- np.sum(dataset.dygame[0,0,1,1,:]))*0,0,(1- np.sum(dataset.dygame[0,1,1,1,:]))*0,0,0,(1- np.sum(dataset.dygame[1,1,0,1,:]))*0,0], \
                                     [(1- np.sum(dataset.dygame[0,0,0,1,:])),1- np.sum(dataset.dygame[0,0,1,1,:]),(1- np.sum(dataset.dygame[0,1,0,1,:])),1- np.sum(dataset.dygame[0,1,1,1,:]),\
                                      (1- np.sum(dataset.dygame[1,0,0,1,:])),(1- np.sum(dataset.dygame[1,0,1,1,:])),1- np.sum(dataset.dygame[1,1,0,1,:]),(1- np.sum(dataset.dygame[1,1,1,1,:]))])          
                                    #  [0,(1- np.sum(dataset.dygame[0,0,1,1,:]))*0,0,(1- np.sum(dataset.dygame[0,1,1,1,:]))*0,0,0,(1- np.sum(dataset.dygame[1,1,0,1,:]))*0,0], \
                                    #  [(1- np.sum(dataset.dygame[0,0,0,1,:])),1- np.sum(dataset.dygame[0,0,1,1,:]),(1- np.sum(dataset.dygame[0,1,0,1,:])),1- np.sum(dataset.dygame[0,1,1,1,:]),\
                                    #   (1- np.sum(dataset.dygame[1,0,0,1,:])),(1- np.sum(dataset.dygame[1,0,1,1,:])),1- np.sum(dataset.dygame[1,1,0,1,:]),(1- np.sum(dataset.dygame[1,1,1,1,:]))])  
# resbrute1 = optimize.brute(LogLike_MLE1, rranges, full_output=True,
#                           finish=optimize.fmin)
x0 = np.array([0.05,0.5,0.11764706,0.25,0.1875 ,0.33333333,0.27272727,0.1])

res = minimize(func1, x0,constraints=[linear_constraint])#,
               #options={'verbose': 3})#, bounds=bounds)
theta1 = np.array([res.x[0], 1- np.sum(dataset.dygame[0,0,0,1,:])-res.x[0],dataset.dygame[0,0,0,1,0],dataset.dygame[0,0,0,1,1],\
                                                res.x[1], 1- np.sum(dataset.dygame[0,0,1,1,:])-res.x[1],dataset.dygame[0,0,1,1,0],dataset.dygame[0,0,1,1,1],\
                                                res.x[2], 1- np.sum(dataset.dygame[0,1,0,1,:])-res.x[2],dataset.dygame[0,1,0,1,0],dataset.dygame[0,1,0,1,1],\
                                                res.x[3], 1- np.sum(dataset.dygame[0,1,1,1,:])-res.x[3],dataset.dygame[0,1,1,1,0],dataset.dygame[0,1,1,1,1],\
                                                res.x[4], 1- np.sum(dataset.dygame[1,0,0,1,:])-res.x[4],dataset.dygame[1,0,0,1,0],dataset.dygame[1,0,0,1,1],\
                                                res.x[5], 1- np.sum(dataset.dygame[1,0,1,1,:])-res.x[5],dataset.dygame[1,0,1,1,0],dataset.dygame[1,0,1,1,1],\
                                                res.x[6], 1- np.sum(dataset.dygame[1,1,0,1,:])-res.x[6],dataset.dygame[1,1,0,1,0],dataset.dygame[1,1,0,1,1],\
                                                res.x[7], 1- np.sum(dataset.dygame[1,1,1,1,:])-res.x[7],dataset.dygame[1,1,1,1,0],dataset.dygame[1,1,1,1,1]])
#Minimize a function over a given range by brute force.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in log


In [10]:
np.round(theta1.reshape([2,2,2,2,2]),5),res.fun

(array([[[[[0.03489, 0.46511],
           [0.4    , 0.1    ]],
 
          [[0.51312, 0.48688],
           [0.     , 0.     ]]],
 
 
         [[[0.11637, 0.29539],
           [0.23529, 0.35294]],
 
          [[0.23179, 0.14321],
           [0.5    , 0.125  ]]]],
 
 
 
        [[[[0.1989 , 0.2386 ],
           [0.25   , 0.3125 ]],
 
          [[0.31532, 0.39302],
           [0.20833, 0.08333]]],
 
 
         [[[0.25569, 0.10795],
           [0.63636, 0.     ]],
 
          [[0.11397, 0.48603],
           [0.05   , 0.35   ]]]]]), 30018.18951179606)

In [11]:
print(dataset.dygame-theta1.reshape([2,2,2,2,2]))

[[[[[ 0.01510617 -0.01510617]
    [ 0.          0.        ]]

   [[-0.01311657  0.01311657]
    [ 0.          0.        ]]]


  [[[ 0.0012726  -0.0012726 ]
    [ 0.          0.        ]]

   [[ 0.01821489 -0.01821489]
    [ 0.          0.        ]]]]



 [[[[-0.01140032  0.01140032]
    [ 0.          0.        ]]

   [[ 0.01801651 -0.01801651]
    [ 0.          0.        ]]]


  [[[ 0.01703648 -0.01703648]
    [ 0.          0.        ]]

   [[-0.01397373  0.01397373]
    [ 0.          0.        ]]]]]


In [12]:
#from scipy.optimize import brute
rranges = (slice(3, 5, 0.5), slice(3, 5, 0.5))
from scipy import optimize

# func = lambda theta2_dk: LogLike_MLE2(np.array([theta2[0,0,0],theta2[0,0,1],theta2[0,1,0],theta2_dk[0],\
#                                                 theta2[1,0,0],theta2[1,0,1],theta2[1,1,0],theta2_dk[1]]),theta1)
func = lambda theta2_dk: LogLike_MLE2(np.array([theta2[0,0,0],theta2[0,0,1],theta2[0,1,0],theta2_dk[0],\
                                                theta2[1,0,0],theta2[1,0,1],theta2[1,1,0],theta2_dk[1]]),theta1.reshape([2,2,2,2,2]))
# resbrute = optimize.brute(func, rranges, full_output=True,
#                           finish=optimize.fmin)

bounds = [[3,5],[3,5]]
resbrute = minimize(func, [3.18,4.57], method='L-BFGS-B',#'trust-constr', #options={'verbose': 3}, 
                    bounds=bounds)
#Minimize a function over a given range by brute force.

[[[3.2  3.86]
  [3.86 3.18]]

 [[2.69 3.58]
  [3.58 4.57]]] 60469.01848520613
[[[3.2        3.86      ]
  [3.86       3.18000001]]

 [[2.69       3.58      ]
  [3.58       4.57      ]]] 60469.018485351815
[[[3.2        3.86      ]
  [3.86       3.18      ]]

 [[2.69       3.58      ]
  [3.58       4.57000001]]] 60469.01848555756
[[[3.2  3.86]
  [3.86 3.  ]]

 [[2.69 3.58]
  [3.58 3.  ]]] 62360.47787411829
[[[3.2        3.86      ]
  [3.86       3.00000001]]

 [[2.69       3.58      ]
  [3.58       3.        ]]] 62360.477863227345
[[[3.2        3.86      ]
  [3.86       3.        ]]

 [[2.69       3.58      ]
  [3.58       3.00000001]]] 62360.47785421653
[[[3.2        3.86      ]
  [3.86       3.17788565]]

 [[2.69       3.58      ]
  [3.58       4.55155821]]] 60468.708418133116
[[[3.2        3.86      ]
  [3.86       3.17788566]]

 [[2.69       3.58      ]
  [3.58       4.55155821]]] 60468.708418038645
[[[3.2        3.86      ]
  [3.86       3.17788565]]

 [[2.69       3.58      ]
  [3

In [13]:
resbrute#87

      fun: 60468.67798164991
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>
      jac: array([-0.02837623,  0.06548362])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 18
      nit: 4
   status: 0
  success: True
        x: array([3.18506421, 4.5483982 ])

In [14]:
#from scipy.optimize import brute
rranges = (slice(3, 5, 0.5), slice(3, 5, 0.5))
from scipy import optimize

# func = lambda theta2_dk: LogLike_MLE2(np.array([theta2[0,0,0],theta2[0,0,1],theta2[0,1,0],theta2_dk[0],\
#                                                 theta2[1,0,0],theta2[1,0,1],theta2[1,1,0],theta2_dk[1]]),theta1)
func = lambda theta2_dk: LogLike_MLE2(np.array([theta2[0,0,0],theta2[0,0,1],theta2[0,1,0],theta2_dk[0],\
                                                theta2[1,0,0],theta2[1,0,1],theta2[1,1,0],theta2_dk[1]]),dataset.dygame)
# resbrute = optimize.brute(func, rranges, full_output=True,
#                           finish=optimize.fmin)

bounds = [[3,5],[3,5]]
resbrute = minimize(func, [3.18,4.57], method='L-BFGS-B',#'trust-constr', #options={'verbose': 3}, 
                    bounds=bounds)
#Minimize a function over a given range by brute force.

[[[3.2  3.86]
  [3.86 3.18]]

 [[2.69 3.58]
  [3.58 4.57]]] 60462.459270229876
[[[3.2        3.86      ]
  [3.86       3.18000001]]

 [[2.69       3.58      ]
  [3.58       4.57      ]]] 60462.45927049294
[[[3.2        3.86      ]
  [3.86       3.18      ]]

 [[2.69       3.58      ]
  [3.58       4.57000001]]] 60462.459270308325
[[[3.2  3.86]
  [3.86 3.  ]]

 [[2.69 3.58]
  [3.58 3.  ]]] 62362.78415607597
[[[3.2        3.86      ]
  [3.86       3.00000001]]

 [[2.69       3.58      ]
  [3.58       3.        ]]] 62362.784145090656
[[[3.2        3.86      ]
  [3.86       3.        ]]

 [[2.69       3.58      ]
  [3.58       3.00000001]]] 62362.78413636876
[[[3.2        3.86      ]
  [3.86       3.17937119]]

 [[2.69       3.58      ]
  [3.58       4.56451536]]] 60462.43175318255
[[[3.2        3.86      ]
  [3.86       3.1793712 ]]

 [[2.69       3.58      ]
  [3.58       4.56451536]]] 60462.43175337225
[[[3.2        3.86      ]
  [3.86       3.17937119]]

 [[2.69       3.58      ]
  [3.

In [15]:
resbrute#87

      fun: 60462.232549567496
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>
      jac: array([-0.04511094, -0.06330083])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 18
      nit: 4
   status: 0
  success: True
        x: array([3.16052035, 4.57748151])

In [ ]:
# [[[3.2  3.86]
#   [3.41 3.18]]

#  [[2.69 3.58]
#   [2.75 4.57]]]
# [[[[[0.05       0.45      ]
#     [0.4        0.1       ]]

#    [[0.5        0.5       ]
#     [0.         0.        ]]]


#   [[[0.11764706 0.29411765]
#     [0.23529412 0.35294118]]

#    [[0.25       0.125     ]
#     [0.5        0.125     ]]]]



#  [[[[0.1875     0.25      ]
#     [0.25       0.3125    ]]

#    [[0.33333333 0.375     ]
#     [0.20833333 0.08333333]]]


#   [[[0.27272727 0.09090909]
#     [0.63636364 0.        ]]

#    [[0.1        0.5       ]
#     [0.05       0.35      ]]]]]
# -30569.377627952916
# [[[3.2  3.86]
#   [3.41 3.18]]

#  [[2.69 3.58]
#   [2.75 4.57]]] 45716.60305231534
# -45716.60305231534
# (array([[[[[0.03560498, 0.46439502],
#            [0.4       , 0.1       ]],
 
#           [[0.50324993, 0.49675007],
#            [0.        , 0.        ]]],
 
 
#          [[[0.1263283 , 0.28543641],
#            [0.23529412, 0.35294118]],
 
#           [[0.24384829, 0.13115171],
#            [0.5       , 0.125     ]]]],
 
 
 
#         [[[[0.20293299, 0.23456701],
#            [0.25      , 0.3125    ]],
 
#           [[0.33636311, 0.37197023],
#            [0.20833333, 0.08333333]]],
 
 
#          [[[0.23722995, 0.12640641],
#            [0.63636364, 0.        ]],
 
#           [[0.13576338, 0.46423662],
#            [0.05      , 0.35      ]]]]]), 30563.746733363805)

# [[[[[ 0.01439502 -0.01439502]
#     [ 0.          0.        ]]

#    [[-0.00324993  0.00324993]
#     [ 0.          0.        ]]]


#   [[[-0.00868124  0.00868124]
#     [ 0.          0.        ]]

#    [[ 0.00615171 -0.00615171]
#     [ 0.          0.        ]]]]



#  [[[[-0.01543299  0.01543299]
#     [ 0.          0.        ]]

#    [[-0.00302977  0.00302977]
#     [ 0.          0.        ]]]


#   [[[ 0.03549732 -0.03549732]
#     [ 0.          0.        ]]

#    [[-0.03576338  0.03576338]
#     [ 0.          0.        ]]]]]

#     [[[3.2  3.86]
#   [3.41 3.18]]

#  [[2.69 3.58]
#   [2.75 4.57]]] 110600.85764150915
# [[[3.2        3.86      ]
#   [3.41       3.18000001]]

#  [[2.69       3.58      ]
#   [2.75       4.57      ]]] 110600.8576345339
# [[[3.2        3.86      ]
#   [3.41       3.18      ]]

#  [[2.69       3.58      ]
#   [2.75       4.57000001]]] 110600.8576075167
# [[[3.2  3.86]
#   [3.41 5.  ]]

#  [[2.69 3.58]
#   [2.75 5.  ]]] 88096.70620330972
# [[[3.2        3.86      ]
#   [3.41       5.00000001]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 88096.70625378005
# [[[3.2        3.86      ]
#   [3.41       5.        ]]

#  [[2.69       3.58      ]
#   [2.75       5.00000001]]] 88096.70623173498
# [[[3.2        3.86      ]
#   [3.41       3.55831733]]

#  [[2.69       3.58      ]
#   [2.75       4.65938267]]] 110198.3014160628
# [[[3.2        3.86      ]
#   [3.41       3.55831734]]

#  [[2.69       3.58      ]
#   [2.75       4.65938267]]] 110198.30141709876
# [[[3.2        3.86      ]
#   [3.41       3.55831733]]

#  [[2.69       3.58      ]
#   [2.75       4.65938268]]] 110198.30138509646
# [[[3.2        3.86      ]
#   [3.41       3.46886632]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109145.13295988586
# [[[3.2        3.86      ]
#   [3.41       3.46886633]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109145.13296159732
# [[[3.2        3.86      ]
#   [3.41       3.46886632]]

#  [[2.69       3.58      ]
#   [2.75       5.00000001]]] 109145.13292976118
# [[[3.2        3.86      ]
#   [3.41       3.38945145]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109137.58858977034
# [[[3.2        3.86      ]
#   [3.41       3.38945146]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109137.58858997269
# [[[3.2        3.86      ]
#   [3.41       3.38945145]]

#  [[2.69       3.58      ]
#   [2.75       5.00000001]]] 109137.58855907773
# [[[3.2        3.86      ]
#   [3.41       3.37880343]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109137.48113237476
# [[[3.2        3.86      ]
#   [3.41       3.37880344]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109137.48113237445
# [[[3.2        3.86      ]
#   [3.41       3.37880343]]

#  [[2.69       3.58      ]
#   [2.75       5.00000001]]] 109137.48110160526
# [[[3.2        3.86      ]
#   [3.41       3.37881948]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109137.48113200488
# [[[3.2        3.86      ]
#   [3.41       3.37881949]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109137.48113200495
# [[[3.2        3.86      ]
#   [3.41       3.37881948]]

#  [[2.69       3.58      ]
#   [2.75       5.00000001]]] 109137.4811012346

  
# [ ]
# from google.colab import drive
# drive.mount('/content/drive')
# Mounted at /content/drive
# [ ]
# # import numpy as np
# # from scipy.special import logsumexp
# # from tqdm import tqdm

# # dim_z = dim_sc = int(2)
# # dim_x = 51

# # dim_ai = int(3)
# # dim_sai = int(2)

# …#           break


# #     return Q_new, pi_new
# [ ]
#                          (1-coef_floor) * Q[np.intc(np.ceil(x[t,:]*(dim_x-1))) * dim_z +state[t,:],0],
# #                             coef_floor * Q[np.intc(np.floor(x[t,:]*(dim_x-1))) * dim_z +state[t,:],1]+\
# #                             (1-coef_floor) * Q[np.intc(np.ceil(x[t,:]*(dim_x-1))) * dim_z +state[t,:],1]]).T
    
# #         pi0 = np.exp(Q_prime[:,0]-Q_prime[:,1])/(np.exp(Q_prime[:,0]-Q_prime[:,1])+1)
# #         action[t,:] = np.intc(np.random.uniform(0,1,size = SampleSize) > pi0).copy()


# Original without Sa
# (Recovering for dynamics still has problems)

# [56]
#       self.T = T
      
#       self.gamma = 0.5772
#       self.beta = 0.9

#       self.blief = 31
#       self.iniccp = np.ones([self.blief,2])/2#np.vstack([np.ones(self.blief),np.zeros(self.blief)]).T

#     def rw(self,s,a1,a2,theta2): # sc in {0,1}, a1,a2 in {0,1}
#       theta2 = np.reshape(theta2,[2,2,2])

# [58]
# import pandas as pd

# np.random.seed(0)
# theta2 = np.random.uniform(1,5,8)
# #print(theta)
# theta2 = np.reshape(pd.Series(theta2).round(2).to_numpy(),[2,2,2])
# #print(theta)
# N = 1500
# T = 30
# x0_dim = 50

# {'state': array([[1, 1, 0, ..., 1, 0, 0],
#        [1, 0, 0, ..., 1, 1, 0],
#        [0, 1, 1, ..., 1, 0, 1],
#        ...,
#        [1, 1, 0, ..., 0, 0, 0],
#        [0, 0, 0, ..., 1, 1, 1],
#        [0, 0, 1, ..., 1, 1, 1]]), 'observation': array([[1, 1, 0, ..., 1, 1, 1],
#        [1, 1, 0, ..., 0, 0, 1],
#        [0, 1, 1, ..., 0, 1, 0],
#        ...,
#        [0, 0, 1, ..., 0, 1, 1],
#        [1, 0, 1, ..., 1, 1, 0],
#        [0, 0, 0, ..., 0, 0, 0]]), 'action1': array([[1, 1, 0, ..., 0, 0, 0],
#        [1, 1, 1, ..., 1, 0, 1],
#        [1, 0, 1, ..., 1, 1, 1],
#        ...,
#        [1, 1, 0, ..., 0, 0, 1],
#        [0, 0, 1, ..., 1, 0, 0],
#        [0, 1, 1, ..., 0, 0, 1]]), 'action2': array([[1, 1, 1, ..., 0, 1, 0],
#        [1, 0, 1, ..., 1, 1, 1],
#        [1, 0, 1, ..., 1, 1, 1],
#        ...,
#        [1, 0, 1, ..., 0, 0, 0],
#        [1, 1, 0, ..., 0, 1, 0],
#        [1, 1, 0, ..., 1, 1, 0]]), 'belief': array([[0.        , 0.58823529, 0.56213018, ..., 0.55680909, 0.9233022 ,
#         0.78891652],
#        [0.02040816, 0.58769793, 0.50348473, ..., 0.34232398, 0.74020665,
#         0.54800604],
#        [0.04081633, 0.60818713, 0.66974048, ..., 0.33463624, 0.57686519,
#         0.37597781],
#        ...,
#        [0.95918367, 0.33614627, 0.30547628, ..., 0.21937391, 0.52500344,
#         0.5160607 ],
#        [0.97959184, 0.99659284, 0.99858076, ..., 0.52371909, 0.91733903,
#         0.13668247],
#        [1.        , 1.        , 0.33333333, ..., 0.8060293 , 0.92046451,
#         0.32726506]])}
# [59]
#     #print(ccp1,ccp2)
#     for ss in range(N):
#       for t in range(T):
#         fl = int(np.floor(blief_x[ss] * (dataset.blief-1)))
#         if fl == dataset.blief-1:
#           pi1 = ccp1[fl,ac1[ss,t]]
#           pi2 = ccp2[fl,ac2[ss,t]]
#         else: 
#           pi1 = ccp1[fl,ac1[ss,t]] * (blief_x[ss] *(dataset.blief-1) - fl) + ccp1[fl+1,ac1[ss,t]]* (1 + fl -blief_x[ss] *(dataset.blief-1)) 
#           pi2 = ccp2[fl,ac2[ss,t]] * (blief_x[ss] *(dataset.blief-1) - fl) + ccp2[fl+1,ac2[ss,t]]* (1 + fl -blief_x[ss] *(dataset.blief-1))

# [60]
# print(theta2)
# print(dataset.dygame)
# print(-LogLike_MLE1(dataset.dygame,params=False))
# print(-LogLike_MLE2(theta2,dataset.dygame,params=True))
# [[[3.2  3.86]
#   [3.41 3.18]]

#  [[2.69 3.58]
#   [2.75 4.57]]]
# [[[[[0.05       0.45      ]
#     [0.4        0.1       ]]

#    [[0.5        0.5       ]
#     [0.         0.        ]]]


#   [[[0.11764706 0.29411765]
#     [0.23529412 0.35294118]]

#    [[0.25       0.125     ]
#     [0.5        0.125     ]]]]



#  [[[[0.1875     0.25      ]
#     [0.25       0.3125    ]]

#    [[0.33333333 0.375     ]
#     [0.20833333 0.08333333]]]


#   [[[0.27272727 0.09090909]
#     [0.63636364 0.        ]]

#    [[0.1        0.5       ]
#     [0.05       0.35      ]]]]]
# -30139.506424484738
# [[[3.2  3.86]
#   [3.41 3.18]]

#  [[2.69 3.58]
#   [2.75 4.57]]] 59336.23787310167
# -59336.23787310167
# [61]
# .11764706,0.25,0.1875 ,0.33333333,0.27272727,0.1])

# res = minimize(func1, x0,constraints=[linear_constraint])#,
#                #options={'verbose': 3})#, bounds=bounds)
# theta1 = np.array([res.x[0], 1- np.sum(dataset.dygame[0,0,0,1,:])-res.x[0],dataset.dygame[0,0,0,1,0],dataset.dygame[0,0,0,1,1],\
#                                                 res.x[1], 1- np.sum(dataset.dygame[0,0,1,1,:])-res.x[1],dataset.dygame[0,0,1,1,0],dataset.dygame[0,0,1,1,1],\
#                                                 res.x[2], 1- np.sum(dataset.dygame[0,1,0,1,:])-res.x[2],dataset.dygame[0,1,0,1,0],dataset.dygame[0,1,0,1,1],\
#                                                 res.x[3], 1- np.sum(dataset.dygame[0,1,1,1,:])-res.x[3],dataset.dygame[0,1,1,1,0],dataset.dygame[0,1,1,1,1],\
#                                                 res.x[4], 1- np.sum(dataset.dygame[1,0,0,1,:])-res.x[4],dataset.dygame[1,0,0,1,0],dataset.dygame[1,0,0,1,1],\
#                                                 res.x[5], 1- np.sum(da
# [48]
# theta1.reshape([2,2,2,2,2]),res.fun
# [49]
# print(dataset.dygame-theta1.reshape([2,2,2,2,2]))
# [55]

# # func = lambda theta2_dk: LogLike_MLE2(np.array([theta2[0,0,0],theta2[0,0,1],theta2[0,1,0],theta2_dk[0],\
# #                                                 theta2[1,0,0],theta2[1,0,1],theta2[1,1,0],theta2_dk[1]]),theta1)
# func = lambda theta2_dk: LogLike_MLE2(np.array([theta2[0,0,0],theta2[0,0,1],theta2[0,1,0],theta2_dk[0],\
#                                                 theta2[1,0,0],theta2[1,0,1],theta2[1,1,0],theta2_dk[1]]),theta1.reshape([2,2,2,2,2]))
# # resbrute = optimize.brute(func, rranges, full_output=True,
# #                           finish=optimize.fmin)

# [[[3.2  3.86]
#   [3.41 3.18]]

#  [[2.69 3.58]
#   [2.75 4.57]]] 110600.85764150915
# [[[3.2        3.86      ]
#   [3.41       3.18000001]]

#  [[2.69       3.58      ]
#   [2.75       4.57      ]]] 110600.8576345339
# [[[3.2        3.86      ]
#   [3.41       3.18      ]]

#  [[2.69       3.58      ]
#   [2.75       4.57000001]]] 110600.8576075167
# [[[3.2  3.86]
#   [3.41 5.  ]]

#  [[2.69 3.58]
#   [2.75 5.  ]]] 88096.70620330972
# [[[3.2        3.86      ]
#   [3.41       5.00000001]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 88096.70625378005
# [[[3.2        3.86      ]
#   [3.41       5.        ]]

#  [[2.69       3.58      ]
#   [2.75       5.00000001]]] 88096.70623173498
# [[[3.2        3.86      ]
#   [3.41       3.55831733]]

#  [[2.69       3.58      ]
#   [2.75       4.65938267]]] 110198.3014160628
# [[[3.2        3.86      ]
#   [3.41       3.55831734]]

#  [[2.69       3.58      ]
#   [2.75       4.65938267]]] 110198.30141709876
# [[[3.2        3.86      ]
#   [3.41       3.55831733]]

#  [[2.69       3.58      ]
#   [2.75       4.65938268]]] 110198.30138509646
# [[[3.2        3.86      ]
#   [3.41       3.46886632]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109145.13295988586
# [[[3.2        3.86      ]
#   [3.41       3.46886633]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109145.13296159732
# [[[3.2        3.86      ]
#   [3.41       3.46886632]]

#  [[2.69       3.58      ]
#   [2.75       5.00000001]]] 109145.13292976118
# [[[3.2        3.86      ]
#   [3.41       3.38945145]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109137.58858977034
# [[[3.2        3.86      ]
#   [3.41       3.38945146]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109137.58858997269
# [[[3.2        3.86      ]
#   [3.41       3.38945145]]

#  [[2.69       3.58      ]
#   [2.75       5.00000001]]] 109137.58855907773
# [[[3.2        3.86      ]
#   [3.41       3.37880343]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109137.48113237476
# [[[3.2        3.86      ]
#   [3.41       3.37880344]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109137.48113237445
# [[[3.2        3.86      ]
#   [3.41       3.37880343]]

#  [[2.69       3.58      ]
#   [2.75       5.00000001]]] 109137.48110160526
# [[[3.2        3.86      ]
#   [3.41       3.37881948]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109137.48113200488
# [[[3.2        3.86      ]
#   [3.41       3.37881949]]

#  [[2.69       3.58      ]
#   [2.75       5.        ]]] 109137.48113200495
# [[[3.2        3.86      ]
#   [3.41       3.37881948]]

#  [[2.69       3.58      ]
#   [2.75       5.00000001]]] 109137.4811012346
# [41]
# resbrute#87
#       fun: 58720.93164104807
#  hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>
#       jac: array([414.64372771, 373.20351112])
#   message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
#      nfev: 6
#       nit: 1
#    status: 0
#   success: True
#         x: array([3., 3.])

# [[[3.2  3.86]
#   [3.41 3.18]]

#  [[2.69 3.58]
#   [2.75 4.57]]] 45716.60305231534
# [[[3.2        3.86      ]
#   [3.41       3.18000001]]

#  [[2.69       3.58      ]
#   [2.75       4.57      ]]] 45716.60305276278
# [[[3.2        3.86      ]
#   [3.41       3.18      ]]

#  [[2.69       3.58      ]
#   [2.75       4.57000001]]] 45716.60305273882
# [[[3.2  3.86]
#   [3.41 3.  ]]

#  [[2.69 3.58]
#   [2.75 3.  ]]] 51152.17018580594
# [[[3.2        3.86      ]
#   [3.41       3.00000001]]

#  [[2.69       3.58      ]
#   [2.75       3.        ]]] 51152.17017232069
# [[[3.2        3.86      ]
#   [3.41       3.        ]]

#  [[2.69       3.58      ]
#   [2.75       3.00000001]]] 51152.17016966529
# [[[3.2        3.86      ]
#   [3.41       3.17950836]]

#  [[2.69       3.58      ]
#   [2.75       4.56571181]]] 45716.406265288475
# [[[3.2        3.86      ]
#   [3.41       3.17950837]]

#  [[2.69       3.58      ]
#   [2.75       4.56571181]]] 45716.40626571284
# [[[3.2        3.86      ]
#   [3.41       3.17950836]]

#  [[2.69       3.58      ]
#   [2.75       4.56571182]]] 45716.40626568289
# [[[3.2        3.86      ]
#   [3.41       3.08975418]]

#  [[2.69       3.58      ]
#   [2.75       3.78285591]]] 48190.40918204452
# [[[3.2        3.86      ]
#   [3.41       3.08975419]]

#  [[2.69       3.58      ]
#   [2.75       3.78285591]]] 48190.409172010426
# [[[3.2        3.86      ]
#   [3.41       3.08975418]]

#  [[2.69       3.58      ]
#   [2.75       3.78285592]]] 48190.40916877501
# [[[3.2        3.86      ]
#   [3.41       3.1792631 ]]

#  [[2.69       3.58      ]
#   [2.75       4.56357259]]] 45716.31333492794
# [[[3.2        3.86      ]
#   [3.41       3.17926311]]

#  [[2.69       3.58      ]
#   [2.75       4.56357259]]] 45716.31333534054
# [[[3.2       3.86     ]
#   [3.41      3.1792631]]

#  [[2.69      3.58     ]
#   [2.75      4.5635726]]] 45716.31333530689
# [[[3.2        3.86      ]
#   [3.41       3.1631221 ]]

#  [[2.69       3.58      ]
#   [2.75       4.51467329]]] 45714.99237548116
# [[[3.2        3.86      ]
#   [3.41       3.16312211]]

#  [[2.69       3.58      ]
#   [2.75       4.51467329]]] 45714.99237552287
# [[[3.2       3.86     ]
#   [3.41      3.1631221]]

#  [[2.69      3.58     ]
#   [2.75      4.5146733]]] 45714.992375500784
# [[[3.2        3.86      ]
#   [3.41       3.16050608]]

#  [[2.69       3.58      ]
#   [2.75       4.5128297 ]]] 45714.98449310119
# [[[3.2        3.86      ]
#   [3.41       3.16050609]]

#  [[2.69       3.58      ]
#   [2.75       4.5128297 ]]] 45714.98449310652
# [[[3.2        3.86      ]
#   [3.41       3.16050608]]

#  [[2.69       3.58      ]
#   [2.75       4.51282971]]] 45714.98449310188
# [[[3.2        3.86      ]
#   [3.41       3.16005724]]

#  [[2.69       3.58      ]
#   [2.75       4.51288777]]] 45714.98437298678
# [[[3.2        3.86      ]
#   [3.41       3.16005725]]

#  [[2.69       3.58      ]
#   [2.75       4.51288777]]] 45714.98437298648
# [[[3.2        3.86      ]
#   [3.41       3.16005724]]

#  [[2.69       3.58      ]
#   [2.75       4.51288778]]] 45714.98437298528
# [[[3.2        3.86      ]
#   [3.41       3.15998333]]

#  [[2.69       3.58      ]
#   [2.75       4.51309922]]] 45714.984351281644
# [[[3.2        3.86      ]
#   [3.41       3.15998334]]

#  [[2.69       3.58      ]
#   [2.75       4.51309922]]] 45714.98435128102
# [[[3.2        3.86      ]
#   [3.41       3.15998333]]

#  [[2.69       3.58      ]
#   [2.75       4.51309923]]] 45714.984351280276

#         fun: 45714.984351281644
#  hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>
#       jac: array([-0.06257324, -0.136788  ])
#   message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
#      nfev: 27
#       nit: 5
#    status: 0
#   success: True
#         x: array([3.15998333, 4.51309922])
